# Generated by Django 5.1.9 on 2025-07-11 08:43

import adl_tahmo_plugin.validators
import django.db.models.deletion
import modelcluster.fields
import timezone_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0017_dataparameter_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='TahmoConnection',
            fields=[
                ('networkconnection_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.networkconnection')),
                ('api_key', models.CharField(max_length=255, verbose_name='API Key')),
                ('api_secret', models.CharField(max_length=255, verbose_name='API Secret')),
            ],
            options={
                'verbose_name': 'TAHMO API Connection',
                'verbose_name_plural': 'TAHMO API Connections',
            },
            bases=('core.networkconnection',),
        ),
        migrations.CreateModel(
            name='TahmoStationLink',
            fields=[
                ('stationlink_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.stationlink')),
                ('tahmo_station_code', models.CharField(max_length=255, verbose_name='Tahmo Station Code')),
                ('timezone', timezone_field.fields.TimeZoneField(default='UTC', help_text='Timezone used by the station for recording observations', verbose_name='Station Timezone')),
                ('start_date', models.DateTimeField(blank=True, help_text='Start date for data pulling. Select a past date to include the historical data. Leave blank for collecting realtime data only', null=True, validators=[adl_tahmo_plugin.validators.validate_start_date], verbose_name='Start Date')),
            ],
            options={
                'verbose_name': 'TAHMO Station Link',
                'verbose_name_plural': 'TAHMO Stations Link',
            },
            bases=('core.stationlink',),
        ),
        migrations.CreateModel(
            name='TahmoStationLinkVariableMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('tahmo_variable_shortcode', models.CharField(max_length=255, verbose_name='TAHMO Variable Shortcode')),
                ('adl_parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dataparameter', verbose_name='ADL Parameter')),
                ('station_link', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='variable_mappings', to='adl_tahmo_plugin.tahmostationlink')),
                ('tahmo_parameter_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.unit', verbose_name='TAHMO Parameter Unit')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
