# Generated by Django 5.1.9 on 2025-07-16 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adl_tahmo_plugin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tahmostationlink',
            name='tahmo_station_code',
            field=models.CharField(max_length=255, verbose_name='Tahmo Station'),
        ),
        migrations.AlterField(
            model_name='tahmostationlinkvariablemapping',
            name='tahmo_variable_shortcode',
            field=models.CharField(max_length=255, verbose_name='TAHMO Variable'),
        ),
    ]
