# Generated by Django 5.1.9 on 2025-08-06 18:19

import adl_tahmo_plugin.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adl_tahmo_plugin', '0002_alter_tahmostationlink_tahmo_station_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tahmostationlink',
            name='start_date',
            field=models.DateTimeField(blank=True, help_text='The date to start collection data for the first collection. Ignored if any data has been collected already for this station', null=True, validators=[adl_tahmo_plugin.validators.validate_start_date], verbose_name='Initial Collection start date'),
        ),
    ]
