# Generated by Django 5.1.9 on 2025-08-11 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adl_tahmo_plugin', '0003_alter_tahmostationlink_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tahmostationlink',
            name='timezone',
        ),
    ]
